default: &default
  adapter: postgresql
  encoding: unicode
  # O 'host' deve ser exatamente o nome do serviço que você colocou no docker-compose.yml
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  # Em produção, geralmente usamos uma URL completa por segurança
  url: <%= ENV.fetch("DATABASE_URL") { "" } %>